apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-service
  namespace: default
spec:
  traffic:
    - latestRevision: true
      percent: 100
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - name: "api-service"
          imagePullPolicy: Always
          image: eu.gcr.io/idyllic-silicon-343409/service
          livenessProbe:
            httpGet:
              path: /health
          ports:
            - name: http1
              containerPort: 8080